<? php
echo '<html>';
echo '<head>';
echo '</head>';
echo '<body>';
echo '<div class="menu">';
echo '</div>';
echo '<div class="main"> THE NEW VIEW HOTEL';
echo '</div>';
echo '<ul>';
echo '<div class="pull-left">';
echo '<li class="dropdown">';
echo '';
echo '<a href="hotelsite.php" class="dropbtn">THE HOTEL</a>';
echo '<div class="dropdown-content">';
echo '<a href="#visionandmission">Vision and Mission</a>';
echo '<a href="#speciality">Speciality</a>';
echo '<a href="#location">Location</a>';
echo '</div>';
echo '</li>';
echo '<li><a href="reservation.php">RESERVATION</a></li>';
echo '<li class="dropdown">';
echo '<a href= "" class="dropbtn">CUISINE</a>';
echo '<div class="dropdown-content">';
echo '<a href="#">Indian</a>';
echo '<a href="#">Italian</a>';
echo '<a href="#">Continental</a>';
echo '</div>';
echo '</li>';
echo '<li><a href="dining.html">DINING</a></li>';
echo '</div>';
echo '<div class="pull-right">';
echo '<li><a href="events.html">EVENTS</a></li>';
echo '<li><a href="gallery1.html">GALLERY</a></li>';
echo '<li><a href="off.html">OFFERS</a></li>';
echo '<li><a href="feedback.html">FEEDBACK</a></li>';
echo '</div>';
echo '</ul>';
echo '</body>';
echo '</html>';
?>